fernetKey: ZXA4QXBtVjNOQjQ5UlBxSzVSQkNEWlBJTVNqYmtSQUY=
webserverSecretKey: 3bdddfea5a72c451b9b0ab4e9b346775
executor: "KubernetesExecutor"

dags:
  gitSync:
    enabled: true
    repo: https://github.com/Sonu-Sukralia/airflowpy.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"

