fernetKey: OTY3aktsMkM2OU0yczdvSWd5bUhLSElUZVhVTzVTd2U=
webserverSecretKey: OTY3aktsMkM2OU0yczdvSWd5bUhLSElUZVhVTzVTd2U=
executor: "KubernetesExecutor"

dags:
  gitSync:
    enabled: true
    repo: https://github.com/Sonu-Sukralia/airflowpy.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"

